[WIP] bootstrap5 + icons
Pylons/deformdemo pull request #124
Opened 2023-11-08 13:12 UTC by delijati

Changes to work with bootstrap5 and bootstrap icons

2023-11-08 13:14 UTC, delijati commented
We should also remove support for python < 3.10!?

2023-11-09 18:36 UTC, delijati commented
Here a preview (will turn it off at some point) http://168.119.117.235:8523/

2023-11-13 22:04 UTC, stevepiercy requested changes
This is great. After I release deform 3.0.0a0, we will need to come back to this and bump that requirement. Thank you!

2023-11-13 22:04 UTC, stevepiercy commented on setup.py
>      "pyramid >= 1.5a1",  # route_name argument to resource_url
By virtue of our Python support, this should be:

```suggestion
    "pyramid >= 2.0a0",  # Drop Python 3.5 support
```

See https://docs.pylonsproject.org/projects/pyramid/en/main/changes.html#id3

2023-11-13 22:05 UTC, stevepiercy commented
This is awesome work. Thank you so much for your effort.

Pylons Project projects try to support currently supported versions of Python when the project is released. Right now [Python 3.8-3.12 are supported](https://devguide.python.org/versions/).

Would you please do two housekeeping tasks before I merge?

- Sign https://github.com/Pylons/deformdemo/blob/main/CONTRIBUTORS.txt
- Update the readme with the supported Python versions. https://github.com/Pylons/deformdemo#deform-demo

2023-11-13 22:36 UTC, stevepiercy requested changes
Python version support

2023-11-13 22:36 UTC, stevepiercy commented on README.rst
I missed this. These need to be updated to drop 3.6 and 3.7, and add 3.10, 3.11, and 3.12.

Same for the trove classifiers in `setup.py`.

2023-11-14 11:08 UTC, stevepiercy requested changes
I did a more thorough review on this pass. A couple of minor changes, and I think it's good to go. Thank you!

2023-11-14 11:08 UTC, stevepiercy commented on .github/workflows/ci-tests.yml
>        uses: actions/setup-python@v2
```suggestion
      uses: actions/setup-python@v4
```

2023-11-14 11:08 UTC, stevepiercy commented on README.rst
> +This application is tested on Python versions >= 3.8 <= 3.12, and PyPy3.
We should write out versions in narrative text.

```suggestion
This application is tested on Python versions 3.8, 3.9, 3.10, 3.11, and 3.12, and PyPy3.
```

2023-11-14 13:23 UTC, merged